import Head from "next/head"
import Layout from "../../components/Layout"


const post = {
  id: '1',
  title: 'New Apex Legends Weapon Revealed, Havoc Arrives Today',
  description: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form',
  thumbnail: 'https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder.png'
}

export default function Post() {
  return (
    <div>
      <Head>
        <title>News | Coders Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width" initial-scale="1.00" maximum-scale="1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-4/5 m-auto min-h-[21.5rem] p-14">
        <div className="w-full">
          <img src={post.thumbnail} alt="Post thumbnail" className="w-full h-[26rem] object-cover rounded-[1.875rem]"/>
        </div>

      </div>
    </div>
  )
}

Post.getLayout = function getLayout(page) {
  return <Layout title={post.title}>{page}</Layout>
}