import Head from 'next/head'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>News | Coders Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-4/5 m-auto bg-white mt-[-42px] rounded-tl-[1.875rem] min-h-[21.5rem] p-6 md:p-14 flex flex-wrap-reverse justify-around">
        <div className="w-[38.75rem] max-h-80">
          <h2 className="font-bold text-[#232323] text-2xl mb-[0.625rem]">New Apex Legends Weapon Revealed, Havoc Arrives Today</h2>
          <p className="text-lg">Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
        </div>
        <div className="w-[35.625rem] max-h-80">
          <img src="https://www.unfe.org/wp-content/uploads/2019/04/SM-placeholder.png" alt="Thumbnail" className="w-full h-full object-cover rounded-[1.25rem]"/>
        </div>
      </div>
    </div> 
  )
}

Home.getLayout = function getLayout(page) {
  return <Layout title="News">{page}</Layout>
}